CREATE TABLE `devweb`.`aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `n1` DOUBLE NOT NULL,
  `n2` DOUBLE NOT NULL,
  `n3` DOUBLE NOT NULL,
  `n4` DOUBLE NOT NULL,
  PRIMARY KEY (`id`));
